### ISSUE TITLE
Flight Gem, or ANGEL_GEM Max Speed change issue

### ISSUE THREAD

**Issue by GrayHay** [ProfElements/DynaTech#126]
## Description (Required)
Ill try to describe this the best that I can. 
My Items.yml file inside of Slimefun folder, has this: 
```
ANGEL_GEM:
  enabled: true
  can-be-used-in-workbenches: false
  hide-in-guide: false
  allow-enchanting: true
  allow-disenchanting: true
  max-flight-speed: 0.3
  has-max-flight-speed: false
```
As you can see, the max flight speed should be 0.3. but it still cycles through 0.1 to 1.0 in-game. I am NOT an OP.

I did restart the server after saving these changes.

## Steps to reproduce the Issue (Required)
listed above ^

## Expected behavior (Required)
The flight speed is to be set to max 0.3 so players can't crash the server

## Server Log / Error Report
no errors in startup/console

## Environment (Required)
![Screenshot 2021-11-28 173120](https://user-images.githubusercontent.com/94946708/143790779-abec79ab-6ac2-48d0-ac59-69dcd1773842.png)

 - Minecraft Version: 1.17.1
 - CS-CoreLib Version: ?
 - Slimefun Version: Listed in above screenshot
 - Plugin Version: Listed in above screenshot
